//code generated by ChatGPT

export const getCountryName = (abbreviation: string) => {
  switch (abbreviation) {
    case 'USA':
      return 'United States of America'
    case 'CAN':
      return 'Canada'
    case 'MEX':
      return 'Mexico'
    case 'GBR':
      return 'United Kingdom of Great Britain and Northern Ireland'
    case 'IRL':
      return 'Ireland'
    case 'FRA':
      return 'France'
    case 'GER':
      return 'Germany'
    case 'ESP':
      return 'Spain'
    case 'ITA':
      return 'Italy'
    case 'GRC':
      return 'Greece'
    case 'NLD':
      return 'Netherlands'
    case 'BEL':
      return 'Belgium'
    case 'CHE':
      return 'Switzerland'
    case 'AUT':
      return 'Austria'
    case 'HUN':
      return 'Hungary'
    case 'POL':
      return 'Poland'
    case 'CZE':
      return 'Czech Republic'
    case 'SVK':
      return 'Slovakia'
    case 'RUS':
      return 'Russian Federation'
    case 'UKR':
      return 'Ukraine'
    case 'BLR':
      return 'Belarus'
    case 'KAZ':
      return 'Kazakhstan'
    case 'UZB':
      return 'Uzbekistan'
    case 'TJK':
      return 'Tajikistan'
    case 'KGZ':
      return 'Kyrgyzstan'
    case 'TKM':
      return 'Turkmenistan'
    case 'CHN':
      return "People's Republic of China"
    case 'JPN':
      return 'Japan'
    case 'KOR':
      return 'Republic of Korea (South Korea)'
    case 'PRK':
      return "Democratic People's Republic of Korea (North Korea)"
    case 'IND':
      return 'India'
    case 'PAK':
      return 'Islamic Republic of Pakistan'
    case 'BGD':
      return "People's Republic of Bangladesh"
    case 'LKA':
      return 'Democratic Socialist Republic of Sri Lanka'
    case 'AUS':
      return 'Commonwealth of Australia'
    case 'NZL':
      return 'New Zealand'
    case 'ARG':
      return 'Argentine Republic'
    case 'BRA':
      return 'Federative Republic of Brazil'
    case 'CHL':
      return 'Republic of Chile'
    case 'COL':
      return 'Republic of Colombia'
    case 'PER':
      return 'Republic of Peru'
    case 'VEN':
      return 'Bolivarian Republic of Venezuela'
    case 'EGY':
      return 'Arab Republic of Egypt'
    case 'MAR':
      return 'Kingdom of Morocco'
    case 'ZAF':
      return 'Republic of South Africa'
    case 'NGA':
      return 'Federal Republic of Nigeria'
    case 'KEN':
      return 'Republic of Kenya'
    case 'ETH':
      return 'Federal Democratic Republic of Ethiopia'
    case 'TZA':
      return 'United Republic of Tanzania'
    case 'COD':
      return 'Democratic Republic of the Congo'
    case 'ZMB':
      return 'Republic of Zambia'
    case 'GUF':
      return 'French Guiana'
    case 'GUY':
      return 'Co-operative Republic of Guyana'
    default:
      return abbreviation
  }
}
